example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wishlist/', include('wishlist.urls')),
    path('', include('example_app.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist_ajax
from wishlist.views import show_wishlist
from wishlist.views import show_xml
from wishlist.views import show_json
from wishlist.views import show_xml_by_id
from wishlist.views import show_json_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import add_barang

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/add/', add_barang, name='add_barang'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse



# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Ibni Shaquille Syauqi Ibrahim',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Ibni Shaquille Syauqi Ibrahim',
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)
@login_required(login_url='/wishlist/login/')
def add_barang(request):
    if request.method == 'POST':
        nama_barang = request.POST.get('nama_barang')
        harga_barang = request.POST.get('harga_barang')
        deskripsi = request.POST.get('deskripsi')
        new_barang = BarangWishlist(nama_barang=nama_barang, harga_barang=harga_barang, deskripsi=deskripsi)
        new_barang.save()
    return redirect('wishlist:show_wishlist_ajax')


def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")
def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")
def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist_ajax")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return redirect('wishlist:login')

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <title>
      
      {% block meta %}
        
      {% endblock meta %}
        
    </title>
    <style>
      .login {
        margin-top: 10%;
        margin-left: 30%;
        margin-right: 30%;
        padding: 40px;
        border-radius: 25px;
        background-color: #51535f;
        color: white;
      }
      .body{
        background-color: #f2f2f2;
      }
    </style>
  </head>
  <body>      
      {% block content %}
        
      {% endblock content %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    Login
{% endblock meta %}

{% block content %}

<div class = "login" >

    <form method="POST" action="" class="d-flex justify-content-center">
        {% csrf_token %}
        <table>
            <tr>
                <td><h5>Username: </h5></td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td><h5>Password: </h5></td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    <p></p>Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a></p>

</div>
{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h5>Formulir Registrasi</h5>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{form.as_table}}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-light ">
	<div class="container-fluid">
		<a class="navbar-brand" href="#">{{nama}}</a>
		<div class="collapse navbar-collapse d-flex justify-content-end" id="navbarSupportedContent">
		  	<button class="btn btn-outline-success " type="submit"><a href="{% url 'wishlist:logout' %}">Logout</a></button>
	  	</div>
	</div>
</nav>

<table class="table">
    <tr>
		<th>#</th>
    	<th scope="col">Nama Barang</th>
		<th scope="col">Harga Barang</th>
    	<th scope="col">Deskripsi</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
	{% for barang in list_barang %}
	<tr>
		<td scope="row">{{forloop.counter}}</td>
		<td>{{barang.nama_barang}}</td>
		<td>{{barang.harga_barang}}</td>
		<td>{{barang.deskripsi}}</td>
	</tr>
	{% endfor %}
</table>
<p class="d-flex justify-content-center">Sesi terakhir login: {{ last_login }}</p>

{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-light ">
	<div class="container-fluid">
		<a class="navbar-brand" href="#">{{nama}}</a>
		<div class="collapse navbar-collapse d-flex justify-content-end" id="navbarSupportedContent">
		  	<button class="btn btn-outline-success " type="submit"><a href="{% url 'wishlist:logout' %}">Logout</a></button>
			<button class="btn btn-outline-success " type="submit" id="addTaskBtn">add task</button>
	  	</div>
	</div>
</nav>

<table class="table">

</table>
<p class="d-flex justify-content-center">Sesi terakhir login: {{ last_login }}</p>

<div id="divForm" >
	<form action="" method="POST">
		{% csrf_token %}
		<div class="form-group">
			<label for="task">nama barang</label>
			<input type="text" class="form-control" id="nama_barang" name="nama_barang" placeholder="Nama Barang">
		</div>
		<div class="form-group">
			<label for="priority">Harga Barang</label>
			<input type="text" class="form-control" id="harga_barang" name="nama_barang" placeholder="Harga Barang">
		</div>
		<div class="form-group">
			<label for="due_date">Deskripsi</label>
			<input type="text" class="form-control" id="deskripsi" name="deskripsi" placeholder="Deskripsi Barang">
		</div>
		<button type="submit" class="btn btn-light" id="submitBtn">Submit</button>
	</form>
</div>


<script>
	$.get( "{% url 'wishlist:show_json' %}", function( data ) {
		document.getElementsByClassName("table")[0].innerHTML = ""
		var table = `
		<tr>
			<th>#</th>
    		<th scope="col">Nama Barang</th>
			<th scope="col">Harga Barang</th>
    		<th scope="col">Deskripsi</th>
    	</tr>
		`;
		for (var i = 0; i < data.length; i++) {
			table += `
			<tr>
				<td scope="row">${i+1}</td>
				<td>${data[i].fields.nama_barang}</td>
				<td>${data[i].fields.harga_barang}</td>
				<td>${data[i].fields.deskripsi}</td>
			</tr>
			`;
		}
		document.getElementsByClassName("table")[0].innerHTML = table;
	});
</script>

<script>
	$(document).ready(function(){	
		$("#divForm").hide();
		$("#addTaskBtn").click(function(){
			$("#divForm").toggle();
		});
	});
</script>

<script>
	$(document).ready(function(){
		$('#submitBtn').click(function(){
			var namaBarang = $('#nama_barang').val();
			var hargaBarang = $('#harga_barang').val();
			var deskripsi = $('#deskripsi').val();
			var CSRFtoken = $('input[name=csrfmiddlewaretoken]').val();
			$.post("{% url 'wishlist:add_barang' %}", {
				nama_barang: namaBarang,
                harga_barang: hargaBarang,
                deskripsi: deskripsi,
                csrfmiddlewaretoken: CSRFtoken,
			}, function(){
				$('.table').empty();
				$.get( "{% url 'wishlist:show_json' %}", function( data ) {
					document.getElementsByClassName("table")[0].innerHTML = ""
					var table = `
					<tr>
						<th>#</th>
						<th scope="col">Nama Barang</th>
						<th scope="col">Harga Barang</th>
						<th scope="col">Deskripsi</th>
					</tr>
					`;
					for (var i = 0; i < data.length; i++) {
						table += `
						<tr>
							<td scope="row">${i+1}</td>
							<td>${data[i].fields.nama_barang}</td>
							<td>${data[i].fields.harga_barang}</td>
							<td>${data[i].fields.deskripsi}</td>
						</tr>
						`;
						
					}
					document.getElementsByClassName("table")[0].innerHTML = table;
				});
			});
		})
	})
</script>

{% endblock content %}